### PR TITLE
Feature/update mmkv - added example project

### PR DESCRIPTION
**Pull request by mateosilguero**

### CODE REVIEW

**Comment by mateosilguero** [comment]
@ammarahm-ed Hi ! could you review this pr ?

MMVK v1.2.3 fix some critical issues https://github.com/Tencent/MMKV/releases/tag/v1.2.3

**Comment by ammarahm-ed** [comment]
Hi @mateosilguero Thanks for adding an example project. I will merge this.

**Comment by mateosilguero** [comment]
Thanks ! 

will you release a new version soon ?

**Comment by ammarahm-ed** [comment]
Yes, after making a few other fixes

**Comment by ammarahm-ed** [comment]
new version released @mateosilguero

**Comment by mateosilguero** [comment]
Thanks a lot !

**Pull request merged**
