### PR TITLE
Fix state bug in useMMKV.js

### PR DESCRIPTION
**Pull request by robinsoncol**
Hey, I'm enjoying this library! Though, I ran into an issue that prevents the UI from updating when `key` and/or `storage` changes in useMMKV.js. This solution seems to reinitialize `value` and `valueType`, but I'm not sure if I covered everything. Let me know if you need more info.

### CODE REVIEW

**Comment by ammarahm-ed** [comment]
Hey I will test this before merging. However why such a use case where we are switching storage instances on the same hook? Can you explain a bit on that part?

**Comment by robinsoncol** [comment]
I was testing code that's structured similarly to this and I need the list of items to change when the `userId` key changes:
```js
const [userId, setUserId] = useState('user-one')
const [userItems, setUserItems] = useStorage(`${userId}:items`)

return (
  <View>
    {userItems && (
      <>
        {userItems.map((item, i) => (
          <Text key={i}>{item}</Text>
        ))}
      </>
    )}
    <Button
      label="Switch user"
      onPress={() => {
	      setUserId(userId === 'user-one' ? 'user-two' : 'user-one')
      }}
    />
    <Button
      label="Add item to user"
      onPress={() => {
	      setUserItems([
		      ...(userItems ? userItems : []),
		      `item-${userItems?.length ?? 0}`
	      ])
      }}
    />
  </View>
)
```
Of course, I can create separate mmkv storage for each user but I thought that was overkill for prototyping.

**Comment by ammarahm-ed** [comment]
@robinsoncol hmm that could be a possible use case. I will merge this. The code looks good.

**Comment by robinsoncol** [comment]
Sweet! Thanks

**Pull request merged**
