### PR TITLE
useMMKVStorage return value if it exists

### PR DESCRIPTION
**Pull request by vokhuyetOz**
Thank you for your awesome library.
When using the useMMKVStorage hook, it always returns null at the first time. Although data is existing.
I changed null to the initial function in useState that return current data of key.
I tested it in my project and it works well.

### CODE REVIEW

**Review by ammarahm-ed — CHANGES_REQUESTED** [review]
This seems to be okay. However you did not set the `valueType` along with `value`. 

I think it would be better to move logic to a `useEffect` with no deps and set both value and valueType?

**Comment by vokhuyetOz** [comment]
Due to valueType will not be used at anywhere at default, so it can be null.
if you want, I think i will implement the same logic for valueType too.
if logic is moved to a `useEffect`, valueType will set to null at default.

**Comment by ammarahm-ed** [comment]
> Due to valueType will not be used at anywhere at default, so it can be null.
> if you want, I think i will implement the same logic for valueType too.
> if logic is moved to a `useEffect`, valueType will set to null at default.
> 

Also just looking closely at the code, i see that we are already calling `updateValue` when the hook is added in a `useEffect`. So the value should not be null when you request it I guess? 

Or are you saying that it is null initially at the very start when a component mounts then it gets populated? 

In the example app, data is not null when app is reloaded from background etc

**Comment by vokhuyetOz** [comment]
> > Due to valueType will not be used at anywhere at default, so it can be null.
> > if you want, I think i will implement the same logic for valueType too.
> > if logic is moved to a `useEffect`, valueType will set to null at default.
> 
> Also just looking closely at the code, i see that we are already calling `updateValue` when the hook is added in a `useEffect`. So the value should not be null when you request it I guess?
> 
> Or are you saying that it is null initially at the very start when a component mounts then it gets populated?
> 
> In the example app, data is not null when app is reloaded from background etc

yes, it was null at the first time useMMKVStorage was called. 
Example: 
`function useAppAccount() {
  const [value, setValue] = useMMKVStorage(mmkvKey, MMKVwithID); return [value, setValue];}`
Whenever i call `const [account]= useAppAccount();` 
`account` always null at default, after that `account` will be the current data.
because `updateValue` is call in `useEffect`. i just make a initial function that return existing data of `key`

**Comment by ammarahm-ed** [comment]
> > > Due to valueType will not be used at anywhere at default, so it can be null.
> > > if you want, I think i will implement the same logic for valueType too.
> > > if logic is moved to a `useEffect`, valueType will set to null at default.
> > 
> > Also just looking closely at the code, i see that we are already calling `updateValue` when the hook is added in a `useEffect`. So the value should not be null when you request it I guess?
> > 
> > Or are you saying that it is null initially at the very start when a component mounts then it gets populated?
> > 
> > In the example app, data is not null when app is reloaded from background etc
> 
> yes, it was null at the first time useMMKVStorage was called. 
> Example: 
> `function useAppAccount() {
>   const [value, setValue] = useMMKVStorage(mmkvKey, MMKVwithID);
>   return [value, setValue];
> }`
> Whenever i call `const [account]= useAppAccount();` 
> `account` always null at default, after that `account` will be the current data.
> because `updateValue` is call in `useEffect`. i just make a initial function that return existing data of `key`

Then i think we don't need to call `updateValue` in useEffect anymore since the value is already loaded by default after the changes you have made.

**Comment by vokhuyetOz** [comment]
> 
<div class="js-timeline-item js-timeline-progressive-focus-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0Njg1OTk4OA==" style="box-sizing: border-box;"><div class="TimelineItem js-comment-container" data-gid="MDEyOklzc3VlQ29tbWVudDg0Njg1OTk4OA==" data-url="/_render_node/MDEyOklzc3VlQ29tbWVudDg0Njg1OTk4OA==/timeline/issue_comment?variables%5BdeferredCommentActions%5D=false" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><div class=" timeline-comment-group js-minimizable-comment-group js-targetable-element TimelineItem-body my-0 " id="issuecomment-846859988" style="box-sizing: border-box; margin-top: 4px; margin-bottom: 0px !important; min-width: 0px; max-width: 100%; color: var(--color-timeline-text); flex: 1 1 auto;"><div class="ml-n3 timeline-comment unminimized-comment comment previewable-edit js-task-list-container js-comment timeline-comment--caret reorderable-task-lists" data-body-version="bbc52085df1d29aa8fb6f2033b01ff70e1942de172c449f4c20d219fb083faf0" data-unfurl-hide-url="/content_reference_attachments/hide" style="box-sizing: border-box; margin-left: -16px !important; position: relative; color: var(--color-text-primary); background-color: var(--color-bg-primary); border: 1px solid var(--color-border-primary); border-radius: 6px;"><div class="edit-comment-hide" style="box-sizing: border-box;"><task-lists disabled="" sortable="" style="box-sizing: border-box;">In the example app, data is not null when app is reloaded from background etc</task-lists></div></div></div></div></div><div class="js-timeline-item js-timeline-progressive-focus-container" style="box-sizing: border-box;"><div class="TimelineItem" style="box-sizing: border-box; position: relative; display: flex; padding: 16px 0px; margin-left: 16px;"><span class="TimelineItem-badge color-bg-info-inverse color-text-white" style="box-sizing: border-box; color: var(--color-icon-secondary); background-color: var(--color-timeline-badge-bg); position: relative; z-index: 1; display: flex; width: 32px; height: 32px; margin-right: 8px; margin-left: -15px; align-items: center; border: 2px solid var(--color-bg-canvas); border-radius: 50%; justify-content: center; flex-shrink: 0; font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><svg aria-hidden="true" viewBox="0 0 16 16" version="1.1" data-view-component="true" height="16" width="16" class="octicon octicon-plus"><path fill-rule="evenodd" d="M7.75 2a.75.75 0 01.75.75V7h4.25a.75.75 0 110 1.5H8.5v4.25a.75.75 0 11-1.5 0V8.5H2.75a.75.75 0 010-1.5H7V2.75A.75.75 0 017.75 2z"></path></svg></span><div class="TimelineItem-body d-flex flex-items-center" style="box-sizing: border-box; align-items: center !important; display: flex !important; min-width: 0px; max-width: 100%; margin-top: 4px; color: var(--color-timeline-text); flex: 1 1 auto; font-family: -apple-system, system-ui, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(13, 17, 23); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><br class="Apple-interchange-newline"></div></div></div>
yes. but when you navigate to other screen, you create new hook of useMMKVStorage, data will be null at initial.

**Comment by vokhuyetOz** [comment]
> > > > Due to valueType will not be used at anywhere at default, so it can be null.
> > > > if you want, I think i will implement the same logic for valueType too.
> > > > if logic is moved to a `useEffect`, valueType will set to null at default.
> > > 
> > > 
> > > Also just looking closely at the code, i see that we are already calling `updateValue` when the hook is added in a `useEffect`. So the value should not be null when you request it I guess?
> > > Or are you saying that it is null initially at the very start when a component mounts then it gets populated?
> > > In the example app, data is not null when app is reloaded from background etc
> > 
> > 
> > yes, it was null at the first time useMMKVStorage was called.
> > Example:
> > `function useAppAccount() { const [value, setValue] = useMMKVStorage(mmkvKey, MMKVwithID); return [value, setValue]; }`
> > Whenever i call `const [account]= useAppAccount();`
> > `account` always null at default, after that `account` will be the current data.
> > because `updateValue` is call in `useEffect`. i just make a initial function that return existing data of `key`
> 
> Then i think we don't need to call `updateValue` in useEffect anymore since the value is already loaded by default after the changes you have made.

Because i can not test it right now. My project is using this awesome library, to make sure it works after the change. Currently, i still keep `updateValue` in `useEffect` 😄

**Pull request merged**
